SELECT FILGRUPPER.FILGRUPPE, INNLESING.DELID, ORGINNLESkobl.KOBLID, ORIGINALFILER.FILID, ORIGINALFILER.FILNAVN, ORIGINALFILER.FORMAT, ORIGINALFILER.IBRUKTIL, ORIGINALFILER.TESTING, INNLESING.RSYNT1, FILGRUPPER.RSYNT_PRE_FGLAGRING
FROM ORIGINALFILER INNER JOIN ((FILGRUPPER INNER JOIN INNLESING ON FILGRUPPER.FILGRUPPE = INNLESING.FILGRUPPE) INNER JOIN ORGINNLESkobl ON (ORGINNLESkobl.DELID = INNLESING.DELID) AND (ORGINNLESkobl.FILGRUPPE = INNLESING.FILGRUPPE) AND (FILGRUPPER.FILGRUPPE = ORGINNLESkobl.FILGRUPPE)) ON ORIGINALFILER.FILID = ORGINNLESkobl.FILID
ORDER BY FILGRUPPER.FILGRUPPE;
